package ventanas;

import aatt.practica03.accesoDNI.ObtenerDatos;
import aatt.practica03.metodosHTTP.*;
import aatt.practica03.model.Usuario;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 * Clase Interfaz, la cual muestra una interfaz grafica de autenticacion
 * mediante un formulario o mediante el uso del DNI.
 * @author Andres Ruiz Peñuela
 * @author Luis Jesús Montes Pérez
 * @version 3.0.0
 */
public class Interfaz extends javax.swing.JFrame {
    /**
     * Constantes
     */
    public final static String direccion = "http://localhost:8080/gr01/autentica";
    public final static String ruta = "Source/datos.txt";
    public final static String ok = "220";
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        //Para que salga centrada.
        this.setLocationRelativeTo(null);
    }
    /**
     * Metodo getIconImage, parap poner un icono
     * @return objeto de tipo Image
     */
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo.jpg"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jLabelIcono = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jUser = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jButtonInicioSesion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonDNI = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(0, 51, 153));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/User.png"))); // NOI18N
        getContentPane().add(jLabelIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 80, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 100, -1));

        jUser.setBackground(new java.awt.Color(0, 0, 102));
        jUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jUser.setForeground(new java.awt.Color(255, 255, 255));
        jUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserActionPerformed(evt);
            }
        });
        getContentPane().add(jUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 288, 160, -1));

        jPassword.setBackground(new java.awt.Color(0, 0, 102));
        jPassword.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 160, -1));

        jButtonInicioSesion.setBackground(new java.awt.Color(0, 0, 102));
        jButtonInicioSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInicioSesion.setText("Iniciar Sesión");
        jButtonInicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonInicioSesionMouseClicked(evt);
            }
        });
        jButtonInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 230, 10));

        jButtonDNI.setBackground(new java.awt.Color(0, 0, 102));
        jButtonDNI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDNI.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDNI.setText("Inicio Sesión con DNI");
        jButtonDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDNIMouseClicked(evt);
            }
        });
        jButtonDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDNIActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 230, 10));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 339, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        //Boton para cerrar la interfaz.
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jButtonInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInicioSesionActionPerformed
    /**
     * Botón para simular un formulario, el cual, realizar una petición POST, 
     * para autenticación.
     * @param evt de tipo java.awt.event.MouseEvent
     * @exception ex de tipo IOException
     */
    private void jButtonInicioSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInicioSesionMouseClicked

        /* Variables */
        String pass;
        String user;
        PeticionPost peti;
        
        /* Inizializacion */
         pass= new String(jPassword.getPassword());
         user= jUser.getText();
         peti=null;
        
        /* Comprobmaos los campos del formulario */
        if(user.equals("") || pass.equals("")){
            //No ha intoducido nombre de usuario o contraseña.
            JOptionPane.showMessageDialog(null,"Error en los datos Usuario o Password.");
        }else{
            //Relleno los campos, procedemos ha realizar la petición Post al servidor.
            //Intanciamos o ejemplariamos a la calse PeticionPost.
            peti = new PeticionPost(direccion,user,pass);
            //Mostramos el resultado.
            try {
                String respuesta = peti.autentica();//Realiamos la petición Post.
                
                //Obtenemos el código, para ello separamos la respuesta
                String[] parts = respuesta.split(" ");
                if(parts[0].equals(ok)){//Si la petición es satisfactoria.
                    JOptionPane.showMessageDialog(null,respuesta);
                    
                    //Llamamos a la tercera interfaz, para indicar el fin.
                    TheEnd ventana = new TheEnd();
                    ventana.setVisible(true);//Mostramos la venta OpenArchivo.
                    this.setVisible(false);  //Ocultamos la ventana Interfaz.
                }else{//Mostramos la respuesta del servidor al usuario.
                    JOptionPane.showMessageDialog(null,respuesta);
                }

            } catch (IOException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex); //Auto-generado
            }
        }
    }//GEN-LAST:event_jButtonInicioSesionMouseClicked
    /**
    * Botón, para realizar una petición POST, mediante el uso del DNI.
    * @param evt
    * @exception ex de tipo IOException
    */
    private void jButtonDNIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDNIMouseClicked
       ByteArrayInputStream bais=null;
       PeticionPost peti=null;
       String respuesta;
       String apodo;
        
        //TAREA 2. Conseguir que el método LeerNIF de ObtenerDatos devuelva el 
        //         correctamente los datos de usuario 
        ObtenerDatos od = new ObtenerDatos();
        Usuario user;
        try {
            user = od.LeerNIF(); //Puede generar una IOException.
            if(user!=null){
               
                //TAREA 3. AUTENTICAR EL CLIENTE CON EL SERVIDOR    
                
                apodo = obApodo(user);//Obtenemos el apodo.
                if(apodo!=null){//Comprobamos si hay un error al obtener el apodo.
                    peti = new PeticionPost(direccion,apodo,user.getNif()); //Intanciamos.
                    respuesta = peti.autentica();//Realizamos la petición.

                    //Mostramos el nombre (no soluciono tíldes y caractes especiales),
                    //el nif, la setenica que se envía, y la respuesta.
                    JOptionPane.showMessageDialog(null,"Acceso DNIe.->\n "
                        +user.toString()+"\n-Apodo: "+apodo
                        +"\n -Envimos: "+peti.getParametros()
                        +"\n-Respuesta: "+respuesta);

                    //Obtenemos el código.
                    String[] parts = respuesta.split(" ");
                    if(parts[0].equals(ok)){
                        //Llamos a la segunda interfaz, para mostrar los datos del DNI.
                        //(Abrimos un TXT)
                        OpenArchivo ventana = new OpenArchivo(ruta);
                        ventana.setVisible(true);//Mostramos la venta OpenArchivo.
                        this.setVisible(false);  //Ocultamos la ventana Interfaz.
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"ACCESO DNIe: Error al leer el NIF.");
                }
                

            }else{
                JOptionPane.showMessageDialog(null,"ACCESO DNIe: Error al leer el NIF.");
            }
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex); //Auto-generado.
            JOptionPane.showMessageDialog(null,"ACCESO DNIe: Error al leer el NIF.");
        } 
    }//GEN-LAST:event_jButtonDNIMouseClicked
    /**
     * Funcion para obtener el apodo.
     * Dado que es un requisito de la  practica el enviar el nombre de usuario 
     * APRuiz, si el nombres es Andrés Ruiz Peñuela.
     * 
     * @param user usuario.
     * @return String, con el apodo.
     * @throws ArrayIndexOutOfBoundsException
     */
    public static String obApodo(Usuario user){
        //Variables
        String apodo;
        char[] name = user.getNombre().toCharArray();
        char[] ap2 = user.getApellido2().toCharArray();
        
        
        try{//Damos formato al apodo.
            apodo= String.valueOf(name[0])+String.valueOf(ap2[0])+user.getApellido1();
        }catch(ArrayIndexOutOfBoundsException e){//Se produjo un error al obtener el apodo.
            System.out.print("Error al obtener el apodo.");
            apodo=null;
        }
        
        return apodo;
    }
    
    private void jButtonDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDNIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDNI;
    private javax.swing.JButton jButtonInicioSesion;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jUser;
    // End of variables declaration//GEN-END:variables
}
